services:
  api:
    # ATTENTION : Si ton repo s'appelle autrement que "devavecdocker", modifie-le ici !
    image: ghcr.io/{{ registry_user | lower }}/devavecdocker/python-api:latest
    restart: always
    ports:
      - "80:8000" # On map le port 80 (Web) vers le 8000 (API)
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ynovpwd
      - POSTGRES_HOST=db
      - DATABASE_URL=postgresql://postgres:ynovpwd@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ynovpwd
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
